#!/bin/sh
set -e

if [ -f /usr/share/debconf/confmodule -a \
     -f /usr/share/dbconfig-common/dpkg/prerm.sqlite3 ]; then
    . /usr/share/debconf/confmodule
    . /usr/share/dbconfig-common/dpkg/prerm.sqlite3
    dbc_go intelmq-webinput-csv-backend "$@"
fi

if [ "$1" = "remove" ] ; then
    . /usr/share/apache2/apache2-maintscript-helper
    apache2_invoke dissite 003_intelmq_webinput_csv.conf
    apache2_invoke disconf intelmq-webinput.conf
fi

#DEBHELPER#
