#Github Workflow to find and notify about misspellings
#
#SPDX-FileCopyrightText: 2020 nic.at GmbH, 2022-2023 Intevation GmbH
#SPDX-License-Identifier: AGPL-3.0-or-later

name: "Codespell spelling check"
on: [push, pull_request]

jobs:
  codespell:
    name: Find and notify about common misspellings
    runs-on: ubuntu-22.04
    # This should not fail the whole workflow run
    continue-on-error: true

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install codespell
      run: pip install codespell
    - name: Run codespell
      run: /home/runner/.local/bin/codespell -S "./client/yarn.lock,./client/src/components,./client/node_modules,./.git"
