#Github Workflow to run pycodestyle
#
#SPDX-FileCopyrightText: 2022-2023 Bundesamt für Sicherheit in der Informationstechnik
#SPDX-License-Identifier: AGPL-3.0-or-later
#Software engineering by Intevation GmbH <https://intevation.de>

name: "Run pycodestyle on repository"

on: [push, pull_request]

jobs:
  pycodestyle:
    name: Run pycodestyle
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install pycodestyle
      run: |
        sudo apt update
        sudo apt install pycodestyle -y
    - name: Run pycodestyle
      run: |
        pycodestyle docs/ intelmq_webinput_csv/ tests/ webinput-adduser webinput_session/
