# Call pytests to run unit tests
#
#SPDX-FileCopyrightText: 2023 Intevation GmbH <swagner@intevation.de>
#SPDX-License-Identifier: AGPL-3.0-or-later
#
name: "Unit tests"
on: [push, pull_request]

jobs:
  unittests:
    runs-on: ubuntu-latest
    name: Run unit tests with pytest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
        with_mailgen: ['true', 'false']


    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: get intelmq dev repository
      uses: actions/checkout@v2
      with:
        repository: wagner-intevation/intelmq
        ref: bot-library
        path: './intelmq'

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install IntelMQ
      run: pip install intelmq/

    - name: get intelmqmail dev repository
      uses: actions/checkout@v2
      with:
        repository: Intevation/intelmq-mailgen
        ref: master
        path: './intelmq-mailgen'
      if: ${{ matrix.with_mailgen == 'true' }}

    - name: Install IntelMQ Mail
      run: pip install ./intelmq-mailgen
      if: ${{ matrix.with_mailgen == 'true' }}

    - name: Install pytest
      run: pip install pytest

    - name: Install
      run: pip install -e .

    - name: Run basic testsuite
      env:
        WEBINPUT_CSV_CONFIG: config/backend/webinput_csv.conf
        WEBINPUT_CSV_SESSION_CONFIG: tests/assets/webinput-session.conf
      run: pytest tests/
      env:
        PYTHONPATH: .
